tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/core"
brew "gcc"
brew "git"
brew "ruby-build"
brew "rbenv"
brew "terraform"
brew "tfenv"
brew "tree"
brew "wget"
brew "mas"
brew "nodenv"
brew 'yarn', args: ["ignore-dependencies"]
brew 'awscli'
brew 'jq'
cask 'android-studio'
cask "alfred"
cask "docker"
cask "kindle"
cask "honto"
cask "dropbox"
cask "homebrew/cask-versions/sequel-pro-nightly"
cask "visual-studio-code"
cask "postman"
cask "google-chrome"
cask "google-japanese-ime"
cask "slack"
cask "iterm2"
cask "ngrok"
cask "amazon-music"
cask "cheatsheet"
cask "appcleaner"
cask "flux"
cask "rescuetime"
cask "discord"
cask "vivaldi"
cask "spectacle"
cask "unity"
cask "stoplight-studio"
cask "boostnote"
cask "google-backup-and-sync"
mas "Xcode", id: 497799835
mas "Pocket", id: 568494494
mas "TweetDeck", id: 485812721
